### ISSUE TITLE
Make it easier to maintain the provided nvim configuration

### ISSUE THREAD

**Issue by lockejan** [nvim-lsp/try.nvim#5]
It's quite tedious to maintain the configuration files right now. 
We should switch to a templating system to keep the friction in maintaining the configuration low.
Sticking to unix tools like sed would also be possible IMO.

Either way, splitting up the config into separate files is necessary.
A helper script (or tool) could then combine them during or before the build step.

**Comment by lockejan** [comment]
It's a nice to have but maybe just fine as it is. Closing for now.

**Comment by mjlbach** [comment]
I'd prefer to address this, I don't mind old open issues

**Comment by lockejan** [comment]
Ok, how come (that this is important)?
I had the impression that we are more inclined to self-contained images.
Handing over the config creation to a templating engine would break this idea.
Except we would keep the configurations inside each image directory.

...

hmm, ok, the more I think about it now, the less I think this is a real issue.
The generated configurations still could be tracked by git.
This way we would have the flexibility and convenience of creating them via the templating solution, but keep an up-to-date rendered config for a self-contained image.
Ok, thanks for challenging. Makes sense now. 😅👍

**Comment by mjlbach** [comment]
Yep, exactly. We could include something like init.lua.template, which includes the boiler plate kickstart configuration with two substitution points, the plugin list and the "LSP" specific part.

**Comment by lockejan** [comment]
Sounds reasonable. I'll see what I can come up with.
