### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by mjlbach** [nvim-lsp/try.nvim#7]
Is `try.nvim` a good name? It's meant to be funny "Try nvim" since containers let you try neovim without mutating the state of your system, but maybe we should go with something dry like `nvim-lsp/containers`

**Comment by lockejan** [comment]
Just to reiterate over my statement, rebranding would be reasonable but I'm fine with just keeping it as it is as well. Shall we put in some work or just close this issue @mjlbach ? (:

**Comment by mjlbach** [comment]
I think the name is fine, it's catchy :)
